name: Java CI with Maven (Backend Tests)

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B clean package --file pom.xml -DskipTests

      - name: Test with Maven
        run: mvn -B test --file pom.xml
